services:
  autoheal:
    image: willfarrell/autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build: ./backend
    environment:
      DATABASE_HOST: db
    labels:
      - "autoheal=true"
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
    restart: unless-stopped
    scale: 3
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: "/api"
    labels:
      - "autoheal=true"
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
    restart: unless-stopped
    scale: 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  db:
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER -h 127.0.0.1 || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    labels:
      - "autoheal=true"
  lb:
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://localhost:80/ping | grep -q 'OK' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
